import psycopg2
from langchain_core.tools import tool
import json

@tool
def fetch_data(sql_query: str) -> str:
    """
    Execute a SQL query on the database and return the resulting data.

    This tool runs a valid SQL SELECT query against the PostgreSQL database
    and retrieves the corresponding rows from the dataset. It is used when
    the agent needs to obtain actual data from the database after generating
    a query.

    Parameters
    ----------
    sql_query : str
        A valid SQL SELECT query generated by the agent.

    Returns
    -------
    str
        The query result serialized as a JSON string containing:

        - columns: list of column names returned by the query
        - rows: list of records returned from the database

    Notes
    -----
    - Only SQL SELECT queries should be executed using this tool.
    - The query must reference existing tables and columns in the database schema.
    - This tool should be used after generating SQL to retrieve data for analysis
      or visualization.
    """
    print("fetch data tool called")
    try:
        conn = psycopg2.connect(
            host="aws-1-ap-southeast-1.pooler.supabase.com",
            database="postgres",
            user="postgres.ddmzvulqgwojyfnswvif",
            password="Soumyajit@185",
            port=5432,
            sslmode="require"
        )
        cur = conn.cursor()
        cur.execute(sql_query)
        rows = cur.fetchall()
        
        # Get column names
        colnames = [desc[0] for desc in cur.description] if cur.description else []
        
        cur.close()
        conn.close()
        
        # Convert to list of dicts for JSON serialization
        result = [dict(zip(colnames, row)) for row in rows]
        print(result)
        return json.dumps(result, default=str)
    except Exception as e:
        return json.dumps({"error": str(e)})
