from langchain_openai import ChatOpenAI
import statistics
from dotenv import load_dotenv
from agent.tools.fetch_db import fetch_data
from langchain_core.tools import tool

load_dotenv()
llm = ChatOpenAI(model="gpt-4o-mini")

MAX_ROWS = 50


def optimize_sql(sql_query: str) -> str:
    """
    Ensure the query does not return huge datasets.
    """
    
    q = sql_query.strip().rstrip(";")

    if "limit" not in q.lower():
        q = f"{q} LIMIT {MAX_ROWS}"

    return q


def compute_statistics(data):
    """
    Extract useful statistics from the dataset.
    """


    if not data:
        return {"summary": "No data returned."}

    keys = list(data[0].keys())

    # assume last column is metric
    metric_col = keys[-1]

    values = [row[metric_col] for row in data if isinstance(row[metric_col], (int, float))]

    stats = {}

    if values:
        stats["max_value"] = max(values)
        stats["min_value"] = min(values)
        stats["avg_value"] = round(statistics.mean(values), 2)

        max_row = max(data, key=lambda x: x[metric_col])
        min_row = min(data, key=lambda x: x[metric_col])

        stats["max_row"] = max_row
        stats["min_row"] = min_row

    stats["row_count"] = len(data)

    return stats


def generate_insights(question, data, stats):
    """
    Use LLM to convert statistical summary into insights.
    """
    print("generate insights tool called")

    prompt = f"""
You are a business intelligence analyst.
You will receive a SQL query and the results from executing it.
Your task is to generate concise insights about the data.

User question:
{question}

Dataset (sample rows):
{data[:10]}

Statistics:
{stats}

Generate 2–3 concise insights explaining the key patterns.
Focus on:
- highest and lowest values
- comparisons
- trends if visible
Avoid repeating numbers excessively.
"""

    response = llm.invoke(prompt)

    return response.content

@tool
def insight_agent(sql_query: str, question: str):
    """
    Generate analytical insights from the result of a SQL query.

    This tool receives a SQL query that represents a data analysis request.
    It executes the query on the database, retrieves the resulting dataset,
    computes basic statistical summaries, and uses a language model to
    generate concise business insights based on the returned data.

    The tool is designed to work with aggregated queries (e.g., GROUP BY,
    SUM, AVG) and should not be used for retrieving large raw datasets.

    Parameters
    ----------
    sql_query : str
        A valid SQL SELECT query generated by another agent or tool.
        The query should preferably return aggregated or summarized data.

    question : str
        The original user question that led to the SQL query.
        This provides context to generate meaningful insights.

    Returns
    -------
    dict
        A dictionary containing:
        - sql_query : the optimized SQL query used for execution
        - data_sample : a small sample of the returned dataset
        - statistics : computed summary statistics (e.g., max, min, average)
        - insights : natural language insights generated from the data

    Notes
    -----
    - The SQL query may be modified internally to enforce limits
      (e.g., LIMIT 50) to prevent large data transfers.
    - The tool summarizes the dataset before sending information
      to the language model to improve performance and reduce cost.
    - This tool should be used when the system needs to explain
      patterns, comparisons, or trends in query results.
    
    """

    try:

        # Step 1 — Optimize SQL
        
        optimized_sql = optimize_sql(sql_query)
        # Step 2 — Execute SQL
        
        columns, rows = fetch_data(optimized_sql)

        data = [dict(zip(columns, row)) for row in rows]

        if not data:
            return {
                "success": True,
                "insights": ["The query returned no results."],
                "data_sample": []
            }

        # Step 3 — Compute statistics
        
        stats = compute_statistics(data)

        # Step 4 — Generate insights
        
        insights = generate_insights(question, data, stats)

        return {
            "success": True,
            "sql_query": optimized_sql,
            "data_sample": data[:10],
            "statistics": stats,
            "insights": insights
        }

    except Exception as e:
        return {
            "success": False,
            "error": str(e)
        }
    
if __name__ == "__main__":
    print(insight_agent('''SELECT region, SUM(revenue) AS total_revenue
FROM sales
GROUP BY region
ORDER BY total_revenue DESC''','show revenue by region')["insights"])